name: any_to_any_converter
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/ankushmishra2903-official/any_to_any_converter
repository: https://github.com/ankushmishra2903-official/any_to_any_converter
issue_tracker: https://github.com/ankushmishra2903-official/any_to_any_converter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
